name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cython
  - sphinx==7.2.6
  - obspy
  - cartopy
  - numpydoc==1.6.0
  - pip
  - pip:
    - sphinx_rtd_theme==1.0.0
    - seislib
